# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zd7BBmEGX0osCJyU3Br-wtqVfUP_JBfW
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

plt.rcParams["figure.figsize"] = (10, 6)
plt.rcParams["font.size"] = 11

god1 = np.array([
    83, 70, 86, 51, 61, 67, 80, 84, 70, 64, 83, 55, 88, 75, 61, 70, 95, 52, 75, 92, 86, 89,
    83, 58, 51, 65, 87, 54, 90, 62, 67, 66, 83, 65, 70, 87, 69, 51, 51, 60, 52, 74, 80, 79,
    85, 85, 92, 22, 92, 57, 84, 92
])

god2 = np.array([
    70, 31, 70, 46, 78, 69, 36, 33, 65, 70, 74, 51, 90, 26, 62, 70, 86, 86, 80, 33, 55, 31,
    69, 31, 62, 63, 86, 55, 69, 62, 31, 90, 31, 31, 69, 64, 57, 75, 53, 89, 0, 31, 81, 53,
    86, 52, 98, 58, 31, 69, 69, 51, 75, 39, 0, 56, 51, 69, 46, 41, 65
])

print(f"год1: n={len(god1)}, min={god1.min()}, max={god1.max()}")
print(f"год2: n={len(god2)}, min={god2.min()}, max={god2.max()}")

# Границы для 5-балльной системы
bins5 = [-0.1, 50, 68, 85, 100]   # -0.1 чтобы 0 попал в интервал
labels5 = ["2", "3", "4", "5"]

# Границы для европейской системы
binsEU = [-0.1, 30, 50, 60, 68, 85, 95, 100]
labelsEU = ["F", "FX", "E", "D", "C", "B", "A"]

# Задание 1: разбиение1_1 и разбиение1_2
razbitie1_1 = pd.cut(god1, bins=bins5, labels=labels5, include_lowest=True)
razbitie1_2 = pd.cut(god1, bins=binsEU, labels=labelsEU, include_lowest=True)

print("разбиение1_1 (5-балльная):")
print(razbitie1_1.value_counts().sort_index())
print("\nразбиение1_2 (европейская):")
print(razbitie1_2.value_counts().sort_index())

# Задание 2: разбиение2_1 и разбиение2_2
razbitie2_1 = pd.cut(god2, bins=bins5, labels=labels5, include_lowest=True)
razbitie2_2 = pd.cut(god2, bins=binsEU, labels=labelsEU, include_lowest=True)

print("разбиение2_1 (5-балльная):")
print(razbitie2_1.value_counts().sort_index())
print("\nразбиение2_2 (европейская):")
print(razbitie2_2.value_counts().sort_index())

# Задание 3: таблица1_1 и таблица2_1
tablica1_1 = razbitie1_1.value_counts().sort_index()
tablica2_1 = razbitie2_1.value_counts().sort_index()

print("таблица1_1 (год1, 5-балльная):")
print(tablica1_1)
print("\nтаблица2_1 (год2, 5-балльная):")
print(tablica2_1)

# Задание 4: таблица1_2 и таблица2_2
tablica1_2 = razbitie1_2.value_counts().sort_index()
tablica2_2 = razbitie2_2.value_counts().sort_index()

print("таблица1_2 (год1, европейская):")
print(tablica1_2)
print("\nтаблица2_2 (год2, европейская):")
print(tablica2_2)

# Задание 5
rel1_1 = tablica1_1 / len(god1)
rel2_1 = tablica2_1 / len(god2)
rel1_2 = tablica1_2 / len(god1)
rel2_2 = tablica2_2 / len(god2)

print("Относительные частоты год1 (5-балльная):")
print(rel1_1.round(3))
print("\nОтносительные частоты год2 (5-балльная):")
print(rel2_1.round(3))
print("\nОтносительные частоты год1 (европейская):")
print(rel1_2.round(3))
print("\nОтносительные частоты год2 (европейская):")
print(rel2_2.round(3))

# Задание 6: barplot по таблица1_1, таблица1_2, таблица2_1, таблица2_2
fig, axes = plt.subplots(2, 2, figsize=(13, 9))

tablica1_1.plot(kind="bar", ax=axes[0, 0], color="steelblue", edgecolor="black")
axes[0, 0].set_title("таблица1_1: год1, 5-балльная")
axes[0, 0].set_ylabel("Частота")
axes[0, 0].tick_params(axis="x", rotation=0)

tablica1_2.plot(kind="bar", ax=axes[0, 1], color="seagreen", edgecolor="black")
axes[0, 1].set_title("таблица1_2: год1, европейская")
axes[0, 1].set_ylabel("Частота")
axes[0, 1].tick_params(axis="x", rotation=0)

tablica2_1.plot(kind="bar", ax=axes[1, 0], color="darkorange", edgecolor="black")
axes[1, 0].set_title("таблица2_1: год2, 5-балльная")
axes[1, 0].set_ylabel("Частота")
axes[1, 0].tick_params(axis="x", rotation=0)

tablica2_2.plot(kind="bar", ax=axes[1, 1], color="firebrick", edgecolor="black")
axes[1, 1].set_title("таблица2_2: год2, европейская")
axes[1, 1].set_ylabel("Частота")
axes[1, 1].tick_params(axis="x", rotation=0)

plt.suptitle("Абсолютные частоты по четырём таблицам", fontsize=14)
plt.tight_layout()
plt.show()

# Задание 7: матрица1 = таблица1_1 + таблица2_1 (5-балльная, оба года)
matrica1 = pd.concat([tablica1_1, tablica2_1], axis=1, keys=["год1", "год2"]).fillna(0).astype(int)

# матрица2 = таблица1_2 + таблица2_2 (европейская, оба года)
matrica2 = pd.concat([tablica1_2, tablica2_2], axis=1, keys=["год1", "год2"]).fillna(0).astype(int)

print("матрица1 (5-балльная):")
print(matrica1)
print("\nматрица2 (европейская):")
print(matrica2)

# Задание 8
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

matrica1.plot(kind="bar", stacked=True, ax=axes[0], edgecolor="black")
axes[0].set_title("матрица1: 5-балльная система")
axes[0].set_ylabel("Частота")
axes[0].tick_params(axis="x", rotation=0)

matrica2.plot(kind="bar", stacked=True, ax=axes[1], edgecolor="black")
axes[1].set_title("матрица2: европейская система")
axes[1].set_ylabel("Частота")
axes[1].tick_params(axis="x", rotation=0)

plt.suptitle("Сравнение год1 и год2", fontsize=14)
plt.tight_layout()
plt.show()

# Задание 9: круговые диаграммы для таблица1_1 ... таблица2_2
fig, axes = plt.subplots(2, 2, figsize=(13, 11))

colors5 = ["#e74c3c", "#f39c12", "#2ecc71", "#3498db"]
colorsEU = ["#e74c3c", "#e67e22", "#f1c40f", "#f39c12", "#2ecc71", "#3498db", "#9b59b6"]

axes[0, 0].pie(tablica1_1, labels=tablica1_1.index, autopct="%1.1f%%",
               colors=colors5, startangle=90)
axes[0, 0].set_title("таблица1_1: год1, 5-балльная")

axes[0, 1].pie(tablica1_2, labels=tablica1_2.index, autopct="%1.1f%%",
               colors=colorsEU[:len(tablica1_2)], startangle=90)
axes[0, 1].set_title("таблица1_2: год1, европейская")

axes[1, 0].pie(tablica2_1, labels=tablica2_1.index, autopct="%1.1f%%",
               colors=colors5, startangle=90)
axes[1, 0].set_title("таблица2_1: год2, 5-балльная")

axes[1, 1].pie(tablica2_2, labels=tablica2_2.index, autopct="%1.1f%%",
               colors=colorsEU[:len(tablica2_2)], startangle=90)
axes[1, 1].set_title("таблица2_2: год2, европейская")

plt.suptitle("Структура оценок: круговые диаграммы", fontsize=14)
plt.tight_layout()
plt.show()